substitutions:
  # -----------------------
  # ADJUST DEVICE NAME HERE
  # -----------------------
  device_name: "homedicator"
  device_friendly_name: "HomeDicator"

  # ---------------------------------------------------------------------------------
  # ENTER API AND OTA KEY HERE
  # Add the keys to your secret file or change them here if you want individual keys.
  # ---------------------------------------------------------------------------------
  ota_key: !secret ota_key
   
  # ------------------------------
  # ADJUST YOUR WLAN SETTINGS HERE
  # ------------------------------
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  # ----------------------------------------------------------------------------------------------------
  # ADJUST TOTAL NUMBER OF PAGES HERE
  # Is used to generate navigation dots and their logic (set it to your pages + 1 for the settings page)
  # ----------------------------------------------------------------------------------------------------
  total_pages: "2"
  
  # --------------
  # OTHER SETTINGS
  # --------------
  page_transition_time: 100ms # How long to animate the transition between pages.
  user_interface_debug_mode: "false" # Draws borders around objects and labels for layouting

packages:
  HomeDicator: !include HomeDicator/device/seeed-sensecap-indicator.yaml

http_request:
  watchdog_timeout: 30s  # Slow response from API server can cause watchdog to reboot device

#logger:
#    level: DEBUG # Set to DEBUG for more information, WARNING for less information.

sensor:
  # ----------------------------------------------------------------------
  # ADD YOUR SENSORS HERE
  # Because of the way ESPHOME works lights, thermostats, etc also go here
  # They need to be included here in order for display to update values.
  # ----------------------------------------------------------------------

  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "indoor_outdoor_meter_47da" # You can ommit the "sensor."
  - !include
      file: HomeDicator/core/templates/volume_media_player.yaml
      vars:
        hass_media_player_id: "top_floor"
  - !include 
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "h5075_a64e_temperature" # You can ommit the "climate."

text_sensor:
   - !include
      file: HomeDicator/core/templates/switch_sensor.yaml
      vars:
         hass_domain: "light"
         hass_entity_id: "elgato_cw43j1a07550"
         icon_on: "\U000F0335" # mdi:lightbulb
         icon_off: "\U000F0336" # mdi:lightbulb-outline
   - !include
      file: HomeDicator/core/templates/switch_sensor.yaml
      vars:
         hass_domain: "light"
         hass_entity_id: "sophias_light"
         icon_on: "\U000F0335" # mdi:lightbulb
         icon_off: "\U000F0336" # mdi:lightbulb-outline
   - !include
      file: HomeDicator/core/templates/media_player.yaml
      vars:
        hass_media_player_id: "top_floor"
        hass_media_player_attribute: "media_title"
   - !include
      file: HomeDicator/core/templates/media_player.yaml
      vars:
        hass_media_player_id: "top_floor"
        hass_media_player_attribute: "media_artist"
   - !include
      file: HomeDicator/core/templates/media_player.yaml
      vars:
        hass_media_player_id: "top_floor"
        hass_media_player_attribute: "media_album_name"
   - !include
      file: HomeDicator/core/templates/state_media_player.yaml
      vars:
        hass_media_player_id: "top_floor"
   - !include
      file: HomeDicator/core/templates/art_media_player.yaml
      vars:
        hass_media_player_id: "top_floor"

binary_sensor:
  # ---------------------
  # ADD YOUR SENSORS HERE
  # ---------------------

switch:
  # ----------------------
  # ADD YOUR SWITCHES HERE
  # ----------------------
online_image:
  - !include
    file: HomeDicator/core/templates/image_media_player.yaml
    vars:
      hass_media_player_id: top_floor

lvgl:  
  pages:
    # ----------------------------
    # ADD / ADJUST YOUR PAGES HERE
    # ----------------------------
    - id: first_page
      bg_opa: TRANSP
      widgets:
        - !include
            file: HomeDicator/user_interface/templates/page_title.yaml
            vars:
              title: "Temperature" # CHANGE PAGE TITLE HERE
        - obj:
            styles: content_container
            layout: 
              type: FLEX
              flex_flow: ROW_WRAP
              flex_align_main: LV_FLEX_ALIGN_START
              flex_align_cross: CENTER            
            widgets:
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "indoor_outdoor_meter_47da"
                    icon: "\U000F02E3"
                    unit: "°F"
                    title: "Outdoor"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "h5075_a64e_temperature"
                    icon: "\U000F02E3"
                    unit: "°F"
                    title: "Family room"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/switch/square.yaml
                  vars:
                    colors: 0xeebf41
                    hass_domain: "light"
                    hass_entity_id: "sophias_light"
                    hass_action: "light.toggle"
                    icon_on: "\U000F0335" # mdi:lightbulb
                    icon_off: "\U000F0336" # mdi:lightbulb-outline
                    title: "Office"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/switch/square.yaml
                  vars:
                    colors: 0xeebf41
                    hass_domain: "light"
                    hass_entity_id: "elgato_cw43j1a07550"
                    hass_action: "light.toggle"
                    icon_on: "\U000F0335" # mdi:lightbulb
                    icon_off: "\U000F0336" # mdi:lightbulb-outline
                    title: "Elgato"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/media_player/wide.yaml
                  vars:
                    hass_media_player_id: "top_floor"
