substitutions:
  # -----------------------
  # ADJUST DEVICE NAME HERE
  # -----------------------
  device_name: "homedicator-development"
  device_friendly_name: "HomeDicator Development"

  # ------------------
  # ENTER API KEY HERE
  # ------------------
  api_key: "<api-key>"

  # ----------------------------------------------------------------------------------------------------
  # ADJUST TOTAL NUMBER OF PAGES HERE
  # Is used to generate navigation dots and their logic (set it to your pages + 1 for the settings page)
  # ----------------------------------------------------------------------------------------------------
  total_pages: "3"

  # --------------
  # OTHER SETTINGS
  # --------------
  page_transition_time: 150ms # How long to animate the transition between pages.
  user_interface_debug_mode: "false" # Draws borders around objects and labels for layouting

packages:
  HomeDicator: !include HomeDicator/device/sdl.yaml

sensor:
  # -----------------------------------------------------------------------
  # ADD YOUR SENSORS HERE
  # Because of the way ESPHOME works lights, thermostats, etc also go here
  # They need to be included here in order for the display to update values.
  # -----------------------------------------------------------------------

  - !include
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "airgradient_schlafzimmer_temperature" # You can ommit the "sensor."

  - !include
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "airgradient_schlafzimmer_senseair_co2_value" # You can ommit the "sensor."

  - !include
      file: HomeDicator/core/templates/sensor.yaml
      vars:
        hass_sensor_id: "airgradient_schlafzimmer_particulate_matter_1_0_m_concentration" # You can ommit the "sensor."

  - !include
      file: HomeDicator/core/templates/climate_sensor_wide.yaml
      vars:
        hass_climate_id: "schlafzimmer_schreibtisch" # You can ommit the "climate."

  - !include
      file: HomeDicator/core/templates/climate_sensor.yaml
      vars:
        hass_climate_id: "wohnzimmer_fenster_links" # You can ommit the "climate."

  - !include
      file: HomeDicator/core/templates/climate_sensor.yaml
      vars:
        hass_climate_id: "kuche" # You can ommit the "climate."

  - !include
      file: HomeDicator/core/templates/climate_sensor_wide.yaml
      vars:
        hass_climate_id: "badezimmer_fenster" # You can ommit the "climate."

  - !include
      file: HomeDicator/core/templates/media_player.yaml
      vars:
        hass_media_player_id: "your_media_player_entity_id" # <--- REPLACE WITH YOUR HOME ASSISTANT MEDIA PLAYER ID (e.g., "living_room_speaker")


binary_sensor:
  # ---------------------
  # ADD YOUR SENSORS HERE
  # ---------------------


switch:
  # ----------------------
  # ADD YOUR SWITCHES HERE
  # ----------------------



lvgl:
  pages:
    # ----------------------------
    # ADD / ADJUST YOUR PAGES HERE
    # ----------------------------
    - id: first_page
      bg_opa: TRANSP
      widgets:
        - !include
            file: HomeDicator/user_interface/templates/page_title.yaml
            vars:
              title: "Temperature" # CHANGE PAGE TITLE HERE
        - obj:
            styles: content_container
            layout:
              type: FLEX
              flex_flow: ROW_WRAP
              flex_align_main: LV_FLEX_ALIGN_START
              flex_align_cross: CENTER
            widgets:
              - !include
                  file: HomeDicator/user_interface/templates/tiles/thermostat/wide_half_height.yaml
                  vars:
                    color: 0xeebf41
                    hass_climate_id: "schlafzimmer_schreibtisch"
                    min_value: 5
                    max_value: 25
                    unit: "°C"
                    icon: "\U000F08A0"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/thermostat/square.yaml
                  vars:
                    color: 0xeebf41
                    hass_climate_id: "wohnzimmer_fenster_links"
                    min_value: 5
                    max_value: 25
                    unit: "°C"
                    title: "Living Room"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/thermostat/square.yaml
                  vars:
                    color: 0xeebf41
                    hass_climate_id: "kuche"
                    min_value: 5
                    max_value: 25
                    unit: "°C"
                    title: "Kittchen"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/thermostat/wide_half_height.yaml
                  vars:
                    color: 0xeebf41
                    hass_climate_id: "badezimmer_fenster"
                    min_value: 5
                    max_value: 25
                    unit: "°C"
                    icon: "\U000F1819"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/media_player/wide.yaml
                  vars:
                    hass_media_player_id: "your_media_player_entity_id" # <--- USE THE SAME ID HERE
    - id: second_page
      bg_opa: TRANSP
      widgets:
        - !include
            file: HomeDicator/user_interface/templates/page_title.yaml
            vars:
              title: "Sensors" # CHANGE PAGE TITLE HERE
        - obj:
            styles: content_container
            layout:
              type: FLEX
              flex_flow: ROW_WRAP
              flex_align_main: LV_FLEX_ALIGN_START
              flex_align_cross: CENTER
            widgets:
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "airgradient_schlafzimmer_temperature"
                    icon: "\U000F0F55"
                    unit: "°C"
                    title: "Bedroom"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/square.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "airgradient_schlafzimmer_senseair_co2_value"
                    icon: "\U000F07E4"
                    unit: "ppm"
                    title: "Bedroom"
              - !include
                  file: HomeDicator/user_interface/templates/tiles/sensor/wide.yaml
                  vars:
                    color: 0xeebf41
                    hass_sensor_id: "airgradient_schlafzimmer_particulate_matter_1_0_m_concentration"
                    icon: "\U000F013B"
                    unit: "µg/m³"
                    title: "Bedroom"
